backend:
  name: github
  repo: lynette367/novel_blog   # 👈 改成你的仓库名
  branch: main
  base_url: novel-blog-8qxh76y5v-lynettes-projects-79681d93.vercel.app
  auth_endpoint: auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "novels"
    label: "Novels"
    folder: "novels"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
